/* Deterministic original art generator. Compile with pp_pixel_art.c and
 * pp_pixel_buffer.c; stdout is the small, uncompressed I4 room source. */
#include "pp_pixel_buffer.h"
#include <stdio.h>
int main(void)
{
    static uint8_t bytes[64+240*148/2]; pp_pixel_buffer_t b;
    pp_pixel_buffer_init(&b,bytes,240,148);
    pp_pixel_sink_t sink={pp_pixel_buffer_rect,&b}; pp_pet_room_draw(&sink);
    puts("/* Generated by pet_art_export.c from original palette pixel art. */\n#include <stdint.h>");
    printf("const uint8_t pp_pet_room_i4[%zu]={\n",sizeof(bytes));
    for(size_t i=0;i<sizeof(bytes);++i) printf("0x%02x,%s",bytes[i],i%24==23?"\n":"");
    puts("\n};"); return fflush(stdout)==0?0:1;
}
